ENT.Type = "anim"
ENT.Base = "base_printer"
 
ENT.PrintName		= "Crappy Printer"
ENT.Author			= "LegendofRobbo"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Category 		= "Money Printers"
ENT.Delay 			= 45
ENT.PayLow			= 15
ENT.PayHigh 		= 25
ENT.PowerUsage		= 1
ENT.Price 			= 200
ENT.Spawnable 		= true
ENT.MaxHealth 		= 200
ENT.Buyer 			= ""
ENT.Flip 			= false
ENT.Model 			= "models/props_c17/consolebox01a.mdl"