ENT.Type = "anim"
ENT.Base = "base_printer"
 
ENT.PrintName		= "Black Hole Printer"
ENT.Author			= "LegendofRobbo"
ENT.Contact			= ""
ENT.Purpose			= ""
ENT.Instructions	= ""
ENT.Category 		= "Money Printers"
ENT.Delay 			= 45
ENT.PayLow			= 5000000
ENT.PayHigh 		= 8000000
ENT.PowerUsage		= 10
ENT.Price 			= 100000000
ENT.Spawnable 		= true
ENT.MaxHealth 		= 400
ENT.Buyer 			= ""
ENT.Flip 			= false
-- ENT.Model 			= "models/props_c17/consolebox01a.mdl"