ENT.Type = "anim"
ENT.Base = "base_structure"
 
ENT.PrintName		= "Industrial Generator"
ENT.Author			= "LegendofRobbo"
ENT.Contact			= "sod off"
ENT.Purpose			= "Gives you electricity for your structures."
ENT.Instructions	= "Keep the wires away from your mouth."
ENT.Category 		= "Power Plants"
ENT.PowerSlots		= 20
ENT.PowerUsage 		= 0
ENT.Price 			= 7000
ENT.PowerDist       = 1024
ENT.Delay 			= 60
ENT.UseCost 		= 50
ENT.Player 			= nil
ENT.Spawnable 		= true
ENT.MaxHealth 		= 600
ENT.Fliped 			= true
ENT.Model 			= "models/props/de_train/de_train_signalbox_01.mdl"